
import "./globals.css";
import {Geist} from  "next/font/google"
import Navbar from "./_component/Navbar";


const geist=Geist({subsets:['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={geist.className}
      >
        
        <Navbar/>
        <div className="  px-8  ">

        {children}
        </div>
        
      </body>
    </html>
  );
}
